# Sentimendianalüüs


## Sisukord

* [Ülesanne 9 ja Boonusülesanne](#9)
* [Andmete lugemine](#lugemine)
* [Sõnade relevantsuse hindamine](#relevants)
* [Logistiline regressioon dokumentide klassifitseerimiseks](#klf)

Põhineb S.Raschka *Python Machine Learnig* raamatu 
[peatükil 8](https://github.com/rasbt/python-machine-learning-book/blob/master/code/ch08) ([*MIT litsents*](https://github.com/rasbt/python-machine-learning-book/blob/master/LICENSE.txt)).

<a id='9'></a>
## Ülesanne 9

Koostada oma originaalandmetest (vt ka Moodle sektsiooni *Iseseisev töö*) .csv fail. Kirjeldada andmestikku lühidalt ja dokumenteerida andmestiku atribuudid eraldi failis kujul **atribuudi_nimi, andmetüüp (tõeväärtus, kategooria, täisarv, reaalarv, tekst, kuupäev,...), selgitus**. Kui on olemas klass või arvväärtus, mida soovime ennustada, siis dokumenteerida ka see.

Või kui originaalandmed puuduvad, siis selle ülesande punktide saamiseks:
Laadida Project Gutenberg lehelt alla Goethe Fausti http://www.gutenberg.org/ebooks/14591 ja Iliase http://www.gutenberg.org/ebooks/6130 tekstifailid (*plain text, utf-8*). Jagada need failid salmideks, kus salme eraldavad kaks reavahetust ja salmipikkus on üle saja ja alla tuhande tähemärgi, näiteks:

`text = file.read()
salmid = [t for t in text.split("\n\n") if 100 < len(t) < 1000]`

Koostage .csv fail, kus read on salmid ja esimeseks veeruks on salmi tekst ning teiseks veeruks on salmi allikas (Ilias või Faust).


## Ülesanne 9.BOONUS


Viige oma originaalandmestik sellisele kujule, mida ka teised tudengid saaksid kasutada ja laadige see Moodlesse üles. Vaadake, et teil oleksid seaduslikud  ja tööalased õigused neid andmeid jagada. Anonümiseerige isikuandmed (kui on) st asendage nimed ja isikukoodid meelevaldsete koodidega.


<a id='lugemine'></a>
## Andmete lugemine

Andmete töötluseks ja movie_data.csv faili koostamiseks on eraldi ipynb märkmik.

In [2]:
import numpy as np
import pandas as pd
import math
from sklearn.feature_extraction.text import CountVectorizer


In [3]:
# Eeldus: movie_data.csv on tekitatud

df = pd.read_csv('./movie_data.csv')
df.head(3)


review  sentiment
0  The House of the Spirits is a gripping tale of...          1
1  I have very fond memories of this film, as I s...          1
2  Seeing this movie always reminds me of what I ...          1

<a id='relevants'></a>
## Sõnade relevantsuse hindamine

Terminisagedus $tf(t, d)$ näitab kui mitu korda termin $t$ esineb dokumendis $d$. Klassi [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) transformeerimismeetod `fit_transform(X)` teisendab tekstimassiivi $t \times d$ terminisagedusmassiiviks.

In [85]:
count = CountVectorizer()
docs = np.array([
    'The sun is shining',
    'The weather is sweet',
    'The sun is shining and weather is sweet'])
bag = count.fit_transform(docs)

print(count.vocabulary_)
print(count.get_feature_names())
print(bag.toarray())

{'the': 5, 'sun': 3, 'is': 1, 'shining': 2, 'weather': 6, 'sweet': 4, 'and': 0}
['and', 'is', 'shining', 'sun', 'sweet', 'the', 'weather']
[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 1 1]]


Sõnad, mis esinevad peaaegu kõigis dokumentides ei ole tavaliselt   dokumentide eristamise mõttes kuigi informatiivsed. Mõõt idf (*inverse document frequency*)  on logaritm dokumentide arvu $n_d$ suhtest sõna $t$ sisaldavate dokumentide arvu $f_d(t)$ ja on seega seda suurem, mida vähemates dokumentides sõna esineb. Vahel modiitseeritakse seda funktsiooni liites jagajale või jagatavale arvu 1.

$$ idf (t) = log \frac{n_d}{f_d(t)} $$

Mõõt **tf-idf** (*term frequency - inverse document frequency*) korrigeerib terminisagedust $tf$ mõõduga $idf$

$$ tfidf (t, d) = tf(i, d) \times idf(t) $$

In [5]:
np.set_printoptions(precision=2)

In [82]:
X = bag.toarray()

def idf(X):
    """ 
    Leiame idf  mõõtude vektori kõigile sõnadele kui meie 
    sagedusmaatriks (bag.toarray()) on X.
    """
    n_d = len(X)
    f_d = np.sum(X != 0, axis=0)
    #print(f_d)
    return np.log(n_d / f_d)

idf(X)


array([1.1 , 0.  , 0.41, 0.41, 0.41, 0.  , 0.41])

In [7]:
def tfidf(X):
    """ 
    Leiame tfidf  sageduste vektori kõigile sõnadele kui meie 
    sagedusmaatriks (bag.toarray()) on X.
    """
    return X * idf(X)

tfidf(X)

array([[0.  , 0.  , 0.41, 0.41, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.41, 0.  , 0.41],
       [1.1 , 0.  , 0.41, 0.41, 0.41, 0.  , 0.41]])

Moodul sklearn pakub selleks klassi [TfidfTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html). Tulemused erinevad seoses funktsioonide veidi  erinevate definitsioonidega 

$$ idf (t) = log \frac{1+n_d}{1+f_d(t)} $$


$$ tfidf (t, d) = tf(i, d) \times (idf(t) + 1) $$

ja dokumendi sagedusvektori normaliseerimisega ühikpikkuseks (L2-normaliseerimine).

In [8]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_t = TfidfTransformer()
tfidf_t.fit_transform(count.fit_transform(docs)).toarray()

array([[0.  , 0.43, 0.56, 0.56, 0.  , 0.43, 0.  ],
       [0.  , 0.43, 0.  , 0.  , 0.56, 0.43, 0.56],
       [0.44, 0.53, 0.34, 0.34, 0.34, 0.26, 0.34]])

<a id='klf'></a>
## Logistiline regressioon dokumentide klassifitseerimiseks





Klass [TfidfVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) lihtsustab tf-idf mõõdu leidmist olles samaväärne  [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) ja [TfidfTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html) üksteise järel rakendamisega. Alustuseks leiame hüperparameetrite otsinguga [GrisSearchCV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.htm) parimad parameetrid. Kasutame selleks ainult 5000 objekti, muidu oleks see samm väga ajamahukas.

In [9]:
X_train = df.loc[:5000, 'review'].values
y_train = df.loc[:5000, 'sentiment'].values
X_test = df.loc[5000:10000, 'review'].values
y_test = df.loc[5000:10000, 'sentiment'].values

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import string

In [11]:
tfidf = TfidfVectorizer(strip_accents=None,
                        lowercase=False,
                        preprocessor=None)

def tokenizer(text):return text.split()
def nopunctuation_tokenizer(text):
    np_text = text.translate({ord(c):None for c in string.punctuation})
    return np_text.split()

param_grid = [{'vect__ngram_range': [(1, 1)],
               'vect__tokenizer': [tokenizer, nopunctuation_tokenizer],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              {'vect__ngram_range': [(1, 1)],
               'vect__tokenizer': [tokenizer, nopunctuation_tokenizer],
               'vect__use_idf':[False],
               'vect__norm':[None],
               'clf__penalty': ['l1', 'l2'],
               'clf__C': [1.0, 10.0, 100.0]},
              ]

lr_tfidf = Pipeline([('vect', tfidf),
                     ('clf', LogisticRegression(random_state=0, solver="liblinear"))])

gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid,
                           scoring='accuracy',
                           cv=5,
                           verbose=1,
                           n_jobs=1)

In [12]:
# Väga ajamahukas samm
gs_lr_tfidf.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed:  1.9min finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('vect',
                                        TfidfVectorizer(analyzer='word',
                                                        binary=False,
                                                        decode_error='strict',
                                                        dtype=<class 'numpy.float64'>,
                                                        encoding='utf-8',
                                                        input='content',
                                                        lowercase=False,
                                                        max_df=1.0,
                                                        max_features=None,
                                                        min_df=1,
                                                        ngram_range=(1, 1),
                                         

In [13]:
print("Parimad parameetrid: ", gs_lr_tfidf.best_params_)
print("\nTäpsus: ", gs_lr_tfidf.best_score_)


Parimad parameetrid:  {'clf__C': 10.0, 'clf__penalty': 'l2', 'vect__ngram_range': (1, 1), 'vect__tokenizer': <function nopunctuation_tokenizer at 0x00000259DF3229D8>}

Täpsus:  0.8638272345530894


Seejärel kasutame neid parameetreid ennustava mudeli treenimiseks andmestiku esimese 25 000 objekti peal ja leiame kõige suurema koefitsendiga (kõige kaalukamad) sõnad otsuse tegemisel.

In [14]:
X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiment'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiment'].values

lr_tfidf.set_params(**gs_lr_tfidf.best_params_)
lr_tfidf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vect',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=False, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='...
                                 tokenizer=<function nopunctuation_tokenizer at 0x00000259DF3229D8>,
                                 use_idf=True, vocabulary=None)),
                ('clf',
                 LogisticRegression(C=10.0, class_weight=None, dual=False,
                                    

Teeme 10-kordse ristkontrolli.

In [15]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(estimator=lr_tfidf,
                         X=X_train,
                         y=y_train,
                         cv=10,
                         n_jobs=1)
print('CV täpsused: ', scores)
print('CV keskmine täpsus: %.3f' % np.mean(scores), "+/- %.3f" % np.std(scores))

CV täpsused:  [0.89 0.9  0.89 0.9  0.9  0.9  0.91 0.89 0.89 0.9 ]
CV keskmine täpsus: 0.897 +/- 0.005


Ja lõpuks kontrollime erinevate meetrikate ja testandmetega.

In [16]:
from sklearn.metrics import accuracy_score, f1_score

y_pred = lr_tfidf.predict(X_test)
print("Täpsus testandmetel:", accuracy_score(y_test, y_pred))
print("F1-skoor testandmetel:", f1_score(y_test, y_pred))

Täpsus testandmetel: 0.89652
F1-skoor testandmetel: 0.896903518909656


In [17]:
coef = lr_tfidf.named_steps['clf'].coef_[0]
print("Koefitsendid:", coef)

Koefitsendid: [-3.89e+00 -1.09e-02 -7.82e-04 ... -2.98e-02 -1.30e-01 -1.12e+00]


In [18]:
word_dict = lr_tfidf.named_steps['vect'].vocabulary_
print("Sõnastik:", len(word_dict))

Sõnastik: 145212


In [19]:
term_coef = [(coef[word_dict[w]], w) for w in word_dict]
term_coef = sorted(term_coef, key=lambda pair: abs(pair[0]), reverse=True)
print("Need sõnad mõjutavad arvustuse sentimenti enim (koefitsent, sõna):\n")
term_coef[:20]

Need sõnad mõjutavad arvustuse sentimenti enim (koefitsent, sõna):



[(-18.581550130186805, 'worst'),
 (-13.953109173385668, 'waste'),
 (-12.84709346084585, 'awful'),
 (-12.18989776865045, 'poor'),
 (-12.071913591071784, 'boring'),
 (-12.05526823169655, 'bad'),
 (11.629898736543854, 'great'),
 (11.217408470171877, 'excellent'),
 (11.16384230825954, '710'),
 (-10.625470462105891, 'nothing'),
 (-10.34525962414036, '410'),
 (-9.678362088776788, 'worse'),
 (-9.602211685977508, 'terrible'),
 (9.383631566601261, 'hilarious'),
 (-9.142327654057086, 'lame'),
 (-9.118222935937693, 'horrible'),
 (8.986600481949363, 'amazing'),
 (-8.836397005665134, 'poorly'),
 (-8.718576934806418, 'fails'),
 (8.631639710122297, 'perfect')]